### ISSUE TITLE
True / true - False / false

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#10]
Il faut que tu remplace : 
"true" par "True"
'false" par False 

Ça pose des problèmes dans le gestion du flag de modification du profile (la petite étoile).

**Comment by DelphinPETER** [comment]
Dans quel fichier ?

**Comment by jpg35310** [comment]
Dans les fichiers Profilexxxxxxx.cfg et dagoma_discoeasy200.def.json.

mais fait attention, j'ai planté mon fichier dagoma_discoeasy200.def.json, c'est peux-tu à cause de cela.

**Comment by jpg35310** [comment]
Suite lecture du fichier de Dagoma-Settings-For-Cura/suivi/Discoeasy200.txt
Suite compréhension des valeurs par défaut fixé dans resources\definitions\dagoma_discoeasy200.def.json
Suite compréhension des valeurs par défaut fixé dans quality\dagoma_discoeasy200*.*

Je te demande de clore ce ticket, je vais ouvrir un ticket par point précis.
(Je commence à comprendre)

**Comment by DelphinPETER** [comment]
Pas de souci, la prochaine étape c'est me proposer directement les modification dans les fichiers :)
