### ISSUE TITLE
Mettre dans le bon ordre (par thème)

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#11]
Peux-tu mettre dans le bon ordre, au moins les thèmes, dans le fichier de définition et dans les fichiers des profiles.

Ex:         
        "machine_gcode_flavor": { "default_value": "DiscoGCode" },
        "machine_heated_bed": { "default_value": False },
        "machine_center_is_zero": { "default_value": False },
        "retraction_speed": { "default_value": 50 },
        "retraction_amount": { "default_value": 3.5 },
        "retraction_enable": { "default_value": True },
        "retraction_min_travel": { "default_value": 1.5 },
        "retraction_hop": { "default_value": 0 },
        "retraction_extra_prime_amount": { "default_value": 3.5 },
        "cool_fan_enabled": { "default_value": True },
        "cool_fan_speed_min": { "default_value": 50 },
        "cool_fan_speed_max": { "default_value": 100 },
        "cool_min_layer_time": { "default_value": 10 },

**Comment by DelphinPETER** [comment]
Oui, c'est vrai que j'utilise tout le temps Ctrl+F, du coup je regarde pas trop l'ordre, mais effectivement ce serai plus lisible.

**Comment by DelphinPETER** [comment]
Ranger par groupe, avec un groupe divers à la fin.
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/443df93d54956777f6bfe2bc74a8193553d9610b
