### ISSUE TITLE
erreur température

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#12]
j'ai généré un fichier d'impression avec CbD et Cura2.3.1
Modèle : Rapide
Filament: PLa Chromatik (205°C)

 **Voici le début du code généré par Cura2.3.1:**
;FLAVOR:RepRap
;TIME:1796
;Generated with Cura_SteamEngine 2.3.1
M104 S205
M109 S205
; -- START GCODE --
G90   ;absolute positioning
M106 S250 ;fan on for the palpeur
G28 X Y
G1 X50
M109 S180
G28
M104 S210

 **Voici le début du code généré par CbD:**
;Gcode by Cura-by-dagoma for DiscoEASY200 V1.0.2
G90   ;absolute positioning
M106 S250 ;fan on for the palpeur
G28 X Y
G1 X50
M109 S180
G28
M104 S215
;Activation palpeur
;bloc palpeur
G29
M107 ;start with the fan off
G1 X100 Y20 F3000
G1 Z0.5
M109 S215

**Conclusion:**
Les deux sont faux....

**_Sur Cura 2.3.1_**
au début du fichier tu a : 
;Generated with Cura_SteamEngine 2.3.1
M104 S205
M109 S205

qui n'a rien à faire là, mais c'est la bonne température
mais le ventilateur n'a pas démarré, car la commande de démarrage est après.

on trouve plus bas :
M109 S180 => ça c'est la préchauffe
G28
M104 S210 => c'est là que ça devrait être à 205
G29
M107 ;start with the fan off
G1 X100 Y20 F3000
G1 Z0.5
M109 S210 => c'est là que ça devrait être à 205

**_Sur Cura by Dagoma_**
C'est dans le bonne ordre, mais il y a un offset de 10°C
M104 S215 => devrait être 205
;Activation palpeur
;bloc palpeur
G29
M107 ;start with the fan off
G1 X100 Y20 F3000
G1 Z0.5
M109 S215 => devrait être 205

J'ai fait le test avec un autre filament qui devait être à 210°C
et j'obtiens : 
M104 S220
;Activation palpeur
;bloc palpeur
G29
M107 ;start with the fan off
G1 X100 Y20 F3000
G1 Z0.5
M109 S220

Ce qui confirme l'offset de 10°C
Qui me semble très bizarre.... 

j'ai fait un test d'impression, et j'ai un meilleur résultat sans l'offset.
je ne sais pas quoi en penser !

**Comment by jpg35310** [comment]
Voici le début de mon GCODE qui fonctionne pour Cura 2.3.1
(J'ai enlevé les commentaires)

; -- START GCODE --
G90 
M106 S250
G28 X Y
G1 X50 
M109 S180
G28
M104 S{material_print_temperature}
G29
M107
G1 X100 Y20 F3000
G1 Z0.5
M109 S{material_print_temperature}


J'ai refait un test d'impression et le début du fichier généré est le suivant:
;FLAVOR:RepRap
;TIME:1796
;Generated with Cura_SteamEngine 2.3.1 
=> Les deux (bonnes) valeurs ont disparu, je ne sais pas pourquoi, mais c'est tant mieux.
; -- START GCODE --  
G90 
M106 S250
G28 X Y
G1 X50 
M109 S180
G28
M104 S205 => c'est la bonne valeur
G29
M107
G1 X100 Y20 F3000
G1 Z0.5
M109 S205 => c'est la bonne valeur

**Comment by DelphinPETER** [comment]
J'ai déjà corrigé ça non ?
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/0777d66b98a8eb50f25ed33db2e568fa397586d3

**Comment by jpg35310** [comment]
Et bien je pensais aussi que tu avais corrigé et j'avais bien compris ton explication, sauf pour la vitesse car à mon sens ça ne marchait pas.

J'ai bien regardé dans le lien 0777d66 et j'ai bien les bon paramètre dans  mon dagoma_discoeasy200.def.json =>Et tout ça me semble bon.

Je vais refaire un test => désinstallation complète et réinstallation complète.
(C'est pourtant ce que j'avais déjà fait)

**Comment by jpg35310** [comment]
Donc j'ai du faire un erreur, c'est bon
(Sauf pour la vitesse => voir à la fin du fichier)

;FLAVOR:RepRap
;TIME:3944
;Generated with Cura_SteamEngine 2.3.1
; -- START GCODE --
**;Vitesse impression = 60
;Vitesse déplacement = 100**
;Température : 205
G90   ;absolute positioning
M106 S250 ;fan on for the palpeur
G28 X Y
G1 X50
M109 S180
G28
M104 S205
G29
M107 ;start with the fan off
G1 X100 Y20 F3000
G1 Z0.5
M109 S205
M82 ;set extruder to absolute mode
G92 E0 ;zero the extruded length
G1 F200 E10 ;extrude 10mm of feed stock
G92 E0 ;zero the extruded length again
G1 Z3
**G1 F60**

La seule erreur est (toujours) G1 F60 qui devrait être G1 F3600
c'est un problème dans Cura 2.3.1 qui ne renvoi pas la bonne valeur, avec les anciennes version de Cura (y compris CbD) c'était bon.

Nota: 
Dans CbD, il mettait la vitesse de déplacement (100x60=6000), mais je pense que c'est une erreur.
sachant que cette valeur est uniquement utilisé pour les lignes G1 ou F n'est pas spécifié.

**Comment by jpg35310** [comment]
Tu peux fermer le case => je vais ouvrir une Case spécifique à la Vitesse et le GCODE.
Je suis en train de me documenter sur ce (vaste) sujet.... et il y a des choses qui me paraissent étrange ou que je ne comprends pas.
