### ISSUE TITLE
erreur vitesse ventilateur

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#13]
Dans les options de Cura 2.3.1 / Personnalisé / Refroidissement
Vitesse du ventilateur : 100.0
	Vitesse régulière du ventilateur : 100.0
	Vitesse maximal du ventilateur : 100.0

Or dans ton fichier tu définis dagoma_discoeasy200.def.json :
        "cool_fan_speed": {
            "maximum_value": "100",
            "default_value": 50
        },

En fait je pense que cette définition, permet d’afficher les warning dans l’interface cura : le changement de couleur du champ de saisie de la valeur.

Par contre si on définit dans un profil « discoeasy200_rapide.inst.cfg » :
cool_fan_speed_min = 50
cool_fan_speed_max = 100
Les bonnes valeurs sont bien remontées dans l’interface.

Donc à corriger par tes soins dans les fichiers.

**Comment by DelphinPETER** [comment]
Ok, c'est bien vu !

**Comment by DelphinPETER** [comment]
J'avais pas compris, mais en faite je pense que beaucoup de paramètres doivent être géré comme ça.
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/3e0c8e4d051b1f2b745a7d93fabc0b1eacb61f68
