### ISSUE TITLE
Suivi paramètre personnalisation JSON et CFG

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#14]
J’ai compris, avec un peu de retard, que tu avais définis un maximum de paramètre dans le fichier JSON => Mais certains ne fonctionnent pas. 
_(Je pensais que la définition était uniquement dans le fichier CFG, c’est pour cela que je suis parti comme un « boulet de canon » pour te donner les différents éléments dans mes posts « brutaux ».)_

Exemple :
J’ai fait un essai en mettant la ligne suivante dans le dagoma_discoeasy200.def.json
"cool_fan_speed_min": { "default_value": 50 }

Qui correspond à : (pour la même définition dans un profils de personnalisation CFG
cool_fan_speed_min = 50

=> Ça ne marche pas

Il faudrait que tu rajout à ton fichier de suivi :
Que ce paramètre X est défini 
•	Soit dans le fichier dagoma_discoeasy200.def.json
•	Soit dans les trois profile type discoeasy200_rapide.inst.cfg

Il est donc nécessaire de vérifier la prise en compte de tous les paramètres que tu as défini dans dagoma_discoeasy200.def.json => l’a tu fais de ton coté

Peut-on faire un fichier de suivi (la vérification) pour ne pas faire la même chose en même temps afin d’être plus efficace ?

**Comment by DelphinPETER** [comment]
J'ai fais la même erreur je pensai que c'était géré dans la conf de l'imprimante (JSON).
Pour info, je découvre tout ça en même temps que toi :), j'ai ma DiscoEasy que depuis un mois.
Pour la gestion des paramètres et où ils sont situer je vais modifier le fichier de suivi pour qu'on puisse gérer ça plus facilement.

**Comment by jpg35310** [comment]
Et moi, j'ai ma disco depuis une semaine aujourd'hui !!!! 
enfin elle était opérationnel dimanche à 2h du matin :)

**Comment by DelphinPETER** [comment]
A compléter : https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/blob/Cura_2.3/suivi/suivi_variables_discoeasy200.md

**Comment by DelphinPETER** [comment]
Je fais le suivi avec le tableau ici => https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/blob/Cura_2.3/suivi/suivi_variables_discoeasy200.md
