### ISSUE TITLE
Erreur / Coque / Epaisseur du dessous

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#15]
Tu as défini dans le fichier JSON
"bottom_thickness": { "default_value": 0.26 },

D’une part ce paramètre n’est pas pris en compte depuis le fichier JSON et doit être défini dans les fichiers CFG des profils.

D'autre part cette valeur me parait erroné vis-à-vis de la description qu’en fait CURA :
Quand on fige la valeur à 0.26 (alors que par défaut c’était : 1), le champ passe en warning.
Normalement cette valeur devrait être un multiple de la hauteur de couche (0.2 pour le profil rapide)

Je pense que c’est une erreur de définition coté DAGOMA.
Je te propose de ne rien définir pour "bottom_thickness"

**Comment by DelphinPETER** [comment]
Bien vu !

**Comment by DelphinPETER** [comment]
Corrigé => https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/51f9c3397ed068ec33e251fb5f027d1bae5e965b
