### ISSUE TITLE
La vitesse d’impression - un vaste sujet – Final => le code qui est produit

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#20]
En introduction : 
J'utilise la pièce "03-PIED_avant_easyUp.STL" dispo sur http://www.thingiverse.com/thing:1944317 comme pièce de référence.

J'analyse le code produit (celui que l'on donne à manger par l'imprimante) par : 
- Cura 2.3.1 avec nos profiles 
- Cura By Dagoma

J'identifie les différences et les trucs qui me paraisse anormal.

Je réalise quelque impression de temps en temps... mais je commence à être à court de filament...

**Comment by jpg35310** [comment]
Synthèse des résultats en termes de temps et consommation de filament:
Cura by Dagoma (Remplissage = 17% / support = aucun / Utilisation du palpeur = Coché / Amélioration de la surface d’adhésion= Coché) : 
- Rapide : 7h23 / 35.77m /108 g
- Standard : 11h48 / 38.67m / 117g
- Fin : 20h59 / 38.04m / 115g


Cura 2.3.1 : 
- Rapide : 8h28 / 33.28m /99g
- Standard : 13h36 / 36.61m / 109g
- Fin : 1j00h29 / 36.37m / 108g


Concernant le fichier produit par les deux versions de Cura :

Premier point troublant :

J’avais fait une réinstallation juste avant ce test, et dans le menu Paramètre/Imprimante/Gérer les imprimantes, j’avais vérifié le contenu du START GECODE :
; -- START GCODE --
;Vitesse impression = {speed_print}
;Vitesse déplacement = {speed_travel}
;Température : {material_print_temperature}
G90 ;absolute positioning
M106 S250 ;fan on for the palpeur
Etc…

Je fais une impression  :
;FLAVOR:RepRap
;TIME:30522
;Generated with Cura_SteamEngine 2.3.1
; -- START GCODE --
;Vitesse impression = 60
;Vitesse déplacement = 100
;Température : 205
G90   ;absolute positioning
M106 S250 ;fan on for the palpeur
Etc…

Ok, no problème :

Je ferme CURA et je relance CURA, je recharge la pièce (oui, je suis un grand malade du test), et j’obtiens le fichier suivant :
;FLAVOR:RepRap
;TIME:30522
;Generated with Cura_SteamEngine 2.3.1
; -- START GCODE --
G90   ;absolute positioning
M106 S250 ;fan on for the palpeur
Etc…

AHHHHHHHHHHHHH je ne suis pas fou, il y a des lignes qui ont disparu !
Et j’ai vérifié dans la configuration, elles ont aussi disparu !!

Néanmoins, c’est bon pour :
…blabla
G28
M104 S{material_print_temperature}
G29
M107 ;start with the fan off
G1 X100 Y20 F3000
G1 Z0.5
M109 S{material_print_temperature}
M82 ;set extruder to absolute mode
Etc…

Mais c'est faut pour la vitesse d'impression: (le truc dont je te parle depuis un moment)
…blabla
G1 F200 E10 ;extrude 10mm of feed stock
G92 E0 ;zero the extruded length again
G1 Z3
G1 F3600 => là c’est une valeur en « dur » alors qu’avant on avait « G1 F{speed_print} »

(Et je refait l'essai trois fois)

!!!!!!!!!!!!!!!!!

J’attends ton retour sur ce sujet, et je ne rajouterais pas d'autres items dans ce poste (je créerais un autre "New issue"

**Comment by jpg35310** [comment]
Suite à des tests dans un poste suivant, je reviens sur ce point => tu peux mettre "G1 F3600" ça fera plaisir à ceux qui n'ont pas compris. 

Mais la "vrai" bonne réponse est : "il ne faut rien mettre car ce paramètre ne sert à rien"

Pour l'histoire des paramètres qui disparaissent, un coup çà me le fait et un autre coup çà ne me le fait pas.... je ne comprends rien. (Bug dans Cura 2.3.1 ???)

Nota: J'ai fais des essais d'impression en supprimant G1 F3600 ou G1 F{la vitesse qui fait plaisir} et il n'y a aucun changement !

**Comment by DelphinPETER** [comment]
J'ai répondu dans un autre message et on en est arrivé à la même conclusion :)
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/issues/21#issuecomment-273579688
