### ISSUE TITLE
La vitesse d’impression - un vaste sujet – Final => Erreur vitesse dans le GCODE

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#21]
A mon sens, les vitesses (par défaut) d’impression et de déplacement sont fausses :
 
Ces valeurs par défaut sont utilisées pour des impressions ou des déplacements où la vitesse n’est pas spécifiée:

Exemple : 
G1 X82.126 Y67.135 E147.28986 => c’est une impression à la vitesse par défaut
G0 X82.126 Y67.135 => c’est un déplacement à la vitesse par défaut

**1er problème :**
Dans le ficher on ne spécifie que la vitesse par défaut de l’impression :
G1 F{speed_print} => (mais qui ne marche pas, c’est l’objet du post précédant, donc ici on considère que ça marche)

La vitesse par défaut du déplacement n’est pas définie, et devrait être :
G0 F{ speed_travel }

**2ième problème :**
Dans Cura By Dagoma seule la vitesse d’impression (G1) est défini, mais avec la valeur de la vitesse de déplacement !!!!
Soit G1 F{ speed_travel }

A mon sens, c’est une erreur, qu’en penses-tu ?

**Analyse :** 
Après, est-ce que je ne me fait pas un nœud au cerveau : 

Pour mémoire : (Profil rapide)
Vitesse d’impression = 60mm/s soit 3600mm/min
Vitesse de déplacement = 100mm/s soit 6000mm/min

;TYPE:SKIRT => là il fait l’entourage de ma pièce
G1 F1020 X44.002 Y36.138 E0.22323 => à la vitesse de 17mm/s
G1 X54.409 Y36.138 E0.67839 => et là la vitesse c’est toujours 17mm/s ou la valeur par défaut ?
G1 X54.409 Y46.407 E1.12752
G1 X133.034 Y35.292 E4.60051
Etc…
G1 X40.393 Y39.747 E21.18139
G0 F6000 X40.793 Y39.913 => déplacement à 100mm/s
G1 F1020 X44.168 Y36.538 E21.39015
G1 X54.009 Y36.538 E21.82056
Etc…
G1 X40.793 Y39.913 E42.24417
G1 F3000 E38.74417 => là il faut un dépôt de matière à l’endroit où la tête se trouve à 50mm/s
G0 F6000 X44.593 Y41.486 => déplacement à 100mm/s
;TYPE:WALL-INNER
G1 F3000 E42.24417
G1 F1020 X45.741 Y40.338 E42.31518
G1 X50.209 Y40.338 E42.51059
G1 X50.209 Y51.243 E42.98754

La question étant :
Lors de ce type de commande :
G1 F1020 X44.002 Y36.138 E0.22323 => à la vitesse de 17mm/s
G1 X54.409 Y36.138 E0.67839 => et là la vitesse c’est toujours 17mm/s ou la valeur par défaut ?

**Comment by jpg35310** [comment]
D'après les tests d'impression que je viens de faire, c'est toujours 17mm/s
Donc je me prends la tête pour rien, mais je comprends beaucoup mieux le fonctionnement du slicer.

Ce qui réponds aussi à une des question précédente (c'est bien je fait les questions et les réponses :) )

Nota: 
Les explications (tuto, tuto vidéo) de certaine personne qui t'explique qu'il faut mieux mettre  "G1 3600" au lieu de "G1 F3000" dans le --- Start GCODE --- n'ont rien compris au fonctionnement du code qui est généré pour l'impression.

**Comment by DelphinPETER** [comment]
J'ai creusé la question de mon coté, j'en déduis que cette commande et juste la commande d'approche avant de commencer vraiment l'impression, la bonne vitesse suivant le profil est appliquée juste après. Elle peut donc être figé à 3600. Par contre, elle ne peut pas être dynamique parce Cura la converti (mm/s=>mm/min) à la volé au moment de la création des commandes, dans le START GCODE, on ne peut que rappeler la valeur de la variable.

Je vais donc la figer à 3600, car actuellement la vitesse d'approche est égale à la vitesse de déplacement mais mm/min au lieu de mm/s.

**Comment by DelphinPETER** [comment]
OK => https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/93f27022a676ed350c94021db69c8bb392a947ea
