### ISSUE TITLE
Support de la Discovery200 

### ISSUE THREAD

**Issue by arthurlutz** [DelphinPETER/DiscoEasy200#23]
En me battant avec les emplacements personnalisables sous linux cf https://github.com/Ultimaker/Cura/issues/847 je me suis rendu les réglages dans ce dépôt concernaient la discoeasy200 alors que j'ai une discovery200.

1ere question : est-ce que ces réglages sont valides aussi pour la discovery200 ? 

2ème remarque : serait-il possible d'avoir aussi la discovery200 dans ce dépot ? Par exemple en faisant des extractions de https://github.com/dagomafr/Cura_by_dagoma/ (notamment le stl utilisable tel quel : https://github.com/dagomafr/Cura_by_dagoma/blob/master/resources/meshes/Discovery_platform.stl )

**Comment by arthurlutz** [comment]
bon, ce n'est pas utilisable "tel quel" le .stl en lien ;-) 

![screenshot from 2017-01-19 22-46-56](https://cloud.githubusercontent.com/assets/108437/22126747/500d8b2a-de99-11e6-8a4c-d4cf0444e31e.png)

**Comment by DelphinPETER** [comment]
Concernant les réglages, je ne connais pas les caractéristiques de la Discovery200, du coup je peux rien confirmer.

Concernant le fichier STL, il faut réorienter le modèle 3D (Pour le DiscoEasy200, je l'ai fait avec SolidWorks et j'en ai profité un peu pour aléger  le modèle d'origine) et refaire le réglage du point 0 dans le fichier de conf

**Comment by DelphinPETER** [comment]
Si je prépare une base de travail vous pouvez la tester ?

**Comment by DelphinPETER** [comment]
Mieux !
![image](https://cloud.githubusercontent.com/assets/2625923/22186746/d98cab5c-e0fa-11e6-87fa-b7a3b93d0625.png)

**Comment by arthurlutz** [comment]
@DelphinPETER cool, tu peux pousser dans le dépot ?

**Comment by Chrysystem** [comment]
@DelphinPETER je tiens a te remercier pour ce boulot car depuis que j'ai ma discoEasy je galérais a retrouvé mes config

merci et continu ...

**Comment by DelphinPETER** [comment]
Je suis en train de structurer le fait d'avoir plusieurs imprimantes avec un seul constructeur. Ça ouvre d'autres possibilités (comme filtrer les matériaux, qualités, etc...) mais je galère pas mal. Du coup je préfère attendre un peu avant de mettre tout ça en ligne.

**Comment by DelphinPETER** [comment]
J'ai rajouté la Discovery200.
J'ai un souci avec cette histoire de palpeur dans la partie GCode, vous pourriez m'éclairer svp.
Merci de vos retour => https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/75170eb53165cedf4e306e1b2e4dd3f68f01b4f9
