### ISSUE TITLE
dagoma_discoeasy200_plateform.s/STL/stl/ dans meshes

### ISSUE THREAD

**Issue by arthurlutz** [DelphinPETER/DiscoEasy200#24]
Pendant que j'y suis, je ne sais pas si c'est problématique, mais le nom de fichier dans la configuration est dagoma_discoeasy200_plateform.stl alors que le nom du fichier dans le dépot est dagoma_discoeasy200_plateform.STL

**Comment by DelphinPETER** [comment]
Corrigé => https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/aae0385a83e43109e5a17f6b1fd572fd72f03d48
