### ISSUE TITLE
Probleme supports d'impression 

### ISSUE THREAD

**Issue by Allanco2** [DelphinPETER/DiscoEasy200#26]
Tout d'abord merci pour votre excellent travail , j'ai trouver un petit bug : impossible pour d'imprimer des support d'impression que se soit :" en contact avec plateau " ou " partout " . impossible d'en avoir .

Avez vous ca chez vous ? 

Merci d'avance

**Comment by DelphinPETER** [comment]
Effectivement j'arrive à reproduire le bug. Je ne pense pas que cela vienne de Cura, si je créai une imprimante custom, la pièce a bien les supports intérieurs et sur le plateau, mais pas avec la DiscoEasy. Je dois fouiller pour trouver d'où cela viens. Merci du retour.

**Comment by DelphinPETER** [comment]
La variable "support_pattern" est vide alors qu'elle devrait être sur 'brim' par défaut. Dès qu'on choisi un type de support, ils apparaissent.

**Comment by DelphinPETER** [comment]
Je me suis embrouillé avec le 'brim', c'est'zigzag'.
Voici la correction : https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/e55ab53f7fc7c8b856724b7e5f64fa6f706b9c35
ATTENTION j'ai modifié le nom des fichiers pour le futur support de la discovery200.

**Comment by Allanco2** [comment]
Bonjour je vient de retransferer le nouveau contenu a l’intérieur de Cura
mais j'ai un autre bug maintenant , les matériaux modifié type chromatik
etc ne sont plus disponible et impossible de les importer via Cura malgres
le message de succes d'importation .

Cordialement


2017-01-29 11:45 GMT+01:00 PETER Delphin <notifications@github.com>:

**Comment by DelphinPETER** [comment]
Il faut nettoyer votre profil Cura et recréer l'imprimante. Le dossier à nettoyer est %user%/AppData/Local/Cura/Cache et si cela ne marche toujours pas carrément %user%/AppData/Local/Cura (attention en supprimant ce dossier vous perdez tous vos paramètres, comme si vous installiez Cura pour la première fois).
