### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AxelBriche** [DelphinPETER/DiscoEasy200#29]
Bonjour, il est écrit "ATTENTION CERTAINS PARAMÈTRES NE SONT PAS ENCORE TRANSFÉRÉS, CES FICHIERS SONT PARTAGÉS POUR ÊTRE TESTÉS."

Vous voulez dire qu'il vaut pour le moment mieux attendre une version plus travaillée avant d'utiliser ces fichiers svp ?

Merci.

**Comment by DelphinPETER** [comment]
Bonjour, j'ai écris cette phrase pour que les utilisateurs de ces fichiers fassent attention et surtout me dédouaner de problèmes si les utilisateurs font n'importe quoi et viennent me le reprocher. Personnellement, j'utilise ces paramètres tous les jours.
