### ISSUE TITLE
Correction des profils

### ISSUE THREAD

**Issue by DelphinPETER** [DelphinPETER/DiscoEasy200#4]
Suite info de jpg35 :

Dans les trois profiles C:\Program Files\Cura 2.3\resources\quality\dagoma_discoeasy200
Section [Values]
rajouter:
material_diameter = 1.74
adhesion_type = skirt (pour la  "jupe") ou brim (pour  "bordure" )

**Comment by DelphinPETER** [comment]
Par défaut c'est "BRIM" ou "NONE", on peut choisir de mettre "NONE" pour le profil "rapide" et "BRIM" pour "standard" et "fin".

**Comment by jpg35310** [comment]
A mon sens, BRIM pour les trois profiles, après c'est juste un choix simple suivant la taille de la pièce.

**Comment by jpg35310** [comment]
J'ai comparé le fichier XML de Cura by Dagoma:

Il y a deux sections, voici la première : ;______________________________________________________________________________________________________________
;Definition de la retraction et de la premiere couche
;______________________________________________________________________________________________________________  <Config_Adv>
    <retraction_speed>50</retraction_speed>
    <retraction_amount>3.5</retraction_amount>
    <bottom_thickness>0.26</bottom_thickness>
    <layer0_width_factor>100</layer0_width_factor>
    <object_sink>0</object_sink>
    <cool_min_layer_time>10</cool_min_layer_time>
    <fan_enabled>True</fan_enabled>
  </Config_Adv>

Et les corrections que je propose pour les profiles de Cura 2.3.1:
<retraction_speed>50</retraction_speed>
il faut rajouter la ligne suivante a nos 3 profiles de Cura 2.3.1
retraction_speed = 50 (de base c'était déja le cas, mais autant la figer)


<retraction_amount>3.5</retraction_amount>
Degré supplémentaire de rétractation primaire:
qui doit génére "G1 F3000 E-3.5" après la phase d'initialisation dans le fichier "dagoma0.g"
retraction_extra_prime_amount = 3.5 (de base il y avait 0)


<bottom_thickness>0.26</bottom_thickness>
Normalement c'est un enfant de "Bottom/Top thickness" qui reprend cette valeur. 
Bottom thickness (mm):
Détermine la hauteur de la couches imprimées sur le fond de l’objet. 
Cette valeur doit toujours être un multiple de la hauteur de couche (x2 ou x3).
dans Cura 2.3.1: 1mm par défaut soit 5 couches en mode rapide et 10 couches en mode fin
à mon sens dans nom modèle par defaut 
la valeur de 0.26 de CbD me parait étrange.
Si quelqu'un à une idée ?


<layer0_width_factor>100</layer0_width_factor>
J'ai lu un message sur le net où cette valeur devrait en faite être à 200
mais de toute facon, je ne retrouve pas ce paramètre dans Cura 2.3.1
Si quelqu'un à une idée ?

<object_sink>0</object_sink>
Si quelqu'un à une idée ?

<cool_min_layer_time>10</cool_min_layer_time>
cool_min_layer_time = 10 (de base c'était déja le cas, mais autant la figer)
       
<fan_enabled>True</fan_enabled>
cool_fan_enabled = true (de base c'était déjà le cas, mais autant la figer)

**Comment by jpg35310** [comment]
Pour la deuxième section : "Definition des caracteristiques du support"
C'est en court, voici déjà les premiers éléments : 

<retraction_min_travel>1.5</retraction_min_travel>
retraction_min_travel = 1.5 (de base il y avait 0.8)

<retraction_combing>True</retraction_combing>
Si quelqu'un à une idée ?
 
<retraction_minimal_extrusion>0.02</retraction_minimal_extrusion>
Si quelqu'un à une idée ?

<retraction_hop>0</retraction_hop>


<skirt_line_count>2</skirt_line_count>
<skirt_gap>3</skirt_gap>
<skirt_minimal_length>150</skirt_minimal_length>
<fan_full_height>0.5</fan_full_height>
A mon sens, il ne faut pas modifier ces trois valeurs qui etait identique pour CbD, 
or dans Cura2.3.1 est sont spécifique à chaque profile.
et il y a déja des spécificités entre nos trois modèles.

<fan_speed>50</fan_speed>
cool_fan_speed_min = 50

<fan_speed_max>100</fan_speed_max>
cool_fan_speed_max = 100

<cool_min_feedrate>20</cool_min_feedrate>
Je comprends la vitesse minimal de fonctionnement du ventillateur
Dans Cura 2.3.1, ce semble fonctionner différement puisqu'il y les paramètre:
- Durée minimale d'un couche (ce qui ralentie la vitesse d'impression !)
- Vitesse minimal (ce qui empèche de trop ralentir) 

<cool_head_lift>False</cool_head_lift>
Je pense, mais pas certain
cool_lift_head = flase (C'etait déja la valeur par defaut dans Cura 2.3.1)

<solid_top>True</solid_top>
support_enable = flase

<solid_bottom>True</solid_bottom>
Je laisse tomber, les supports c'est de toute manière du mode avancé.

Fin: Je bosse sur le reste.

**Comment by jpg35310** [comment]
La version .json à mettre à la fin du fichier.
(Par contre supprime les que tu as écrit pour Fan speed default et Fans speed maxi, c'est pas bon)

        "adhesion_type": { "default_value": skirt },
        "retraction_extra_prime_amount" : { "default_value": 3.5 },
        "cool_min_layer_time" : { "default_value":  10 },
        "cool_fan_enabled": { "default_value": true },
        "retraction_min_travel": { "default_value": 1.5 },
        "cool_fan_speed_min": { "default_value": 50 },
        "cool_fan_speed_max": { "default_value": 100}

**Comment by DelphinPETER** [comment]
C'est mieux d'ouvrir un ticket par demande de modification, il ne faut pas hésiter. Je préfère 20 petits tickets bien ciblé, parce que sinon je ne m'y retrouve pas. Ce ticket concerne uniquement le BRIM vs NONE.

**Comment by jpg35310** [comment]
ok, de plus il y a des soucis.

**Comment by DelphinPETER** [comment]
BRIM ajouté par défaut : 
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/430c93d6f7f0cf380c77481cd01d7f69edc73bc6
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/f1c55561aaa74ef21a46f558cf9d5cba8ae6e24e
