### ISSUE TITLE
Correction du GCode

### ISSUE THREAD

**Issue by DelphinPETER** [DelphinPETER/DiscoEasy200#5]
Proposition de jpg35 : 

; -- START GCODE --
; Initialisation et mise en chauffe à 180°C

G90 ;Toutes les coordonnées exécutées à partir de maintenant sont en rapport à l'origine de la machine
M106 S250 ;Allume les ventilateurs du palpeur (vitesse entre min = 0 et max = 255)
G28 X Y ;Déplacement seulement des axes X et Y vers leurs origines
G1 X50 ;Déplacement Linéaire sur l'axe X de 50mm
M109 S180 ;Définir la température minimal de l'extrudeur et attendre d’être à la bonne température
G28 ;Déplacement de tous les axes vers leurs origines

;M104 S210 en commentaire car dépend du type de filament
M104 S{material_print_temperature} ;Définir la température cible de l’extrudeur et la maintenir 

;Initialisation du palpeur et de l'extruder

G29 ;Déplace l'axe Z sur 5 points, ou plus si c'est prévu dans le Marlin, pour calculer la planéité du plateau
M107 ;Eteindre les ventilateurs
G1 X100 Y20 F3000 ;Déplacement X à 100mm et Y à 20mm à la vitesse de 3000mm/min
G1 Z0.5 ;Déplacement Z à 0.5mm

; M108 S210 en commentaire car dépend du type de filament
M109 S{material_print_temperature} ;Définir la température minimal de l'extrudeur et attendre d'être à la bonne température

M82 ;Défini la position de l'extrudeur en position absolue
G92 E0 ;Défini la position actuelle comme position absolue de l'extruder sans offset
G1 F200 E10 ; Extruder 10mm de manière à la vitesse de 300mm/min   
G92 E0 ;Défini la position actuelle comme position absolue de l'extruder à 0, une seconde fois...
G1 Z3 ;Relever l'axe Z de 3mm, c'est pour dire que la phase d'init est terminé 

;G1 F3600 en commentaire car dépend du type de profil
; 3000mm/min soit 50mm/s
; 3600mm/min soit 60mm/s
; 6000mm/min soit 100mm/s
G1 F{variable vitesse: 6000 ou 3600 ou 3000 } ; Régler la vitesse de déplacement nominal de X Y Z à 3600mm/min soit 60mm/s
; -- end of START GCODE --

**Comment by jpg35310** [comment]
Pour la température la variable est: {material_print_temperature}

F104 S{material_print_temperature} ;Définir la température cible de l’extrudeur et la maintenir 
M109 S{material_print_temperature} ;Définir la température minimal de l'extrudeur et attendre d'être à la bonne température avant de poursuivre

**Comment by jpg35310** [comment]
Pour la la vitesse, c'est moins simple et une explication est nécessaire.

J'ai donc fait une extraction de cette donnée depuis les 3 profiles de Cura by Dagoma : 
En mode fin : G1 F3000 (soit 50mm/s)
En mode standard: G1 F3600  (soit 60mm/s)
en mode rapide: G1 F6000 (soiy 100mm/s)

Il s'agit donc de la vitesse de déplacement et non pas de la vitesse d'impression.

la commande G1 FXXXXX permet de définir une vitesse qui sera utilisé lors de l'utilisation de commande de déplacement où il ne figure pas de vitesse.

Ex: G1 X82.126 Y67.135 E147.28986
Ce qui signifie: se déplace en X Y Z au valeur qui sont indiqué en extrudant (E) une certaine qualité de matière. et le tout sera réalisé à la vitesse pas défaut défini par G1 F??????

Mais à mon sens il y a débat : 

- Normalement les commandes de type G1 X... Y.... E..... c'est pour imprimer, donc on devrait définir G1 F????? à la vitesse d'impression
- Normalement les commandes de type G0 X... Y.... E..... c'est pour les déplacement entre les impression, donc on devrait définir G1 F????? à la vitesse de déplacement

 Ce qui n'est pas le cas des 3 profiles officiel de Curo By Dagoma....

Après, il et aussi possible d'écrire (enfin c'est Cura qui l'écrit) des chose de ce type : 
G0 F3000 X83.347 Y98.055
G1 F1800 X99.356 Y114.064 E35.6909

la vitesse est spécifié, ce ce que fait Cura, mais pas tout le temps.... d’ailleurs, il y a aussi des différence de vitesse pour dans certain cas de figure. C'est d’ailleurs tout l’intérêt de la configuration détaillé de Cura, permettant aussi de gérer des accélérations, des phase d'approches, etc... 

Bref, l'idée est quand même de faire coller les 3 profiles Dagoma de Cura 2.3.1 aux trois profils officiel de Cura by Dagoma. 

Je pense qu'il faut rester sur ce qu'a défini Dagoma.

Donc la variable est {speed_travel}, et non pas {travel_speed}, regarde ton scripte END GCODE.

Mais {speed_travel} renvoie la valeur en mm/s or nous attendons en mm/min.

C'est là que je bloque.

**Comment by DelphinPETER** [comment]
Les deux variables utilisées par Cura sont : speed_travel et speed_print.

Il faut voir le GCode comme l'assemblage de 3 parties le "START GCode"(SGC) + "L'impression de la pièce" +  "End GCode"(EGC)

Pour le SGC et le EGC, les variables sont exprimées en mm/s parce qu'on lui demande la valeur de la variable (implicitement ce sont les valeurs avant conversion).
Quand Cura "écrit" le trajet pour imprimer la pièce il converti à la volé les valeurs en mm/min et inscrits les valeurs a utiliser entre le SGC zet le EGC en tenant compte de type de trajet (impression ou déplacement rapide).

Je sais pas trop si je suis clair.

**Comment by DelphinPETER** [comment]
Variable de la vitesse : 
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/84db95009195bcb0c4e630fb54b0038dd1532ff9

**Comment by DelphinPETER** [comment]
Et la temperature : 
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/commit/0777d66b98a8eb50f25ed33db2e568fa397586d3
