### ISSUE TITLE
Rajout d'une image au lancement de Cura 

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#6]
Ça c'est pour le coté ludique...

![cura](https://cloud.githubusercontent.com/assets/25086392/21904343/8f381ebe-d903-11e6-9f21-457b7dcc1eaf.png)

A mettre dans : 
C:\Program Files\Cura 2.3\resources\images\cura.png

**Comment by DelphinPETER** [comment]
La limite est l'ajout de fichiers de configuration à Cura, pas ça modification.
Après rien n'empêche de faire une version allégé de Cura configuré pour la DiscoEasy. Là, on peut envisager de supprimer les imprimantes, profil, matières,etc... qui ne sont pas utilisés et aussi de modifier les profiles par défaut dans l'onglet "Recommandé". Je pense que vous voyez ou je veux en venir :)

**Comment by jpg35310** [comment]
Ça marche !

Je suis d'accord avec toi.
