### ISSUE TITLE
Choix de la résistance de la pièce

### ISSUE THREAD

**Issue by jpg35310** [DelphinPETER/DiscoEasy200#7]
Dans Cura by Dagoma il y a 3 choix : 
![choix cbd](https://cloud.githubusercontent.com/assets/25086392/21906167/7afde44a-d90a-11e6-82de-89492a8c1525.png)

Et dans Cura 2.3.1 : 
![choix cura 2 3 1](https://cloud.githubusercontent.com/assets/25086392/21906183/8814b032-d90a-11e6-96ec-87c5f9124937.png)

Il faudrait pouvoir modifier : 
- Clairsemé à 17% de remplissage au lieu des 20%
- Dense à 33% de remplissage au lieu des 50%

**Comment by jpg35310** [comment]
Merci beaucoup pour ce travail. C'est exactement ce que je cherchais.

J'ai fais la manip, mais pas encore testé d'impression. Il me reste a étudier les modif de GCODE avant pour ne pas faire de bétise. Je ne sais pas trop quelle version il faut

 

Pour les types de remplissage:

C:\Program Files\Cura 2.3\resources\qml\SidebarSimple.qml

infillModel.append({
                    name: catalog.i18nc("@label", "Light"),
                    percentage: 17,
                    percentageMin: 0,
                    percentageMax: 30,
                    text: catalog.i18nc("@label", "Light (17%) infill will give your model an average strength"),
                    icon: "sparse"
                })
                infillModel.append({
                    name: catalog.i18nc("@label", "Dense"),
                    percentage: 33,
                    percentageMin: 30,
                    percentageMax: 70,
                    text: catalog.i18nc("@label", "Dense (33%) infill will give your model an above average strength"),
                    icon: "dense"
                })

 Par snowzz

En rouge la modif

En bleu la plage min/max. Je ne sais pas trop quoi mettre.

Mon idée: Light -> 0 - 23 Dense 23 - 43. Qu'en pensez vous?

Je précise que je n'ai pas testé non plus cette modif encore. Si quelqu'un test et peut faire un retour

**Comment by DelphinPETER** [comment]
Dans Cura, la gestion est différente elle est directement lié au profil choisi. Dans un premier temps je les ai tous définis à 17%, je pense qu'il serai préférable de mettre l'augmenter en fonction du profil.
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/blob/Cura_2.3/resources/quality/dagoma_discoeasy200/discoeasy200_fin.inst.cfg#L23

Sinon concernant la modification des fichiers voir ma réponse sur le forum (et je viens de voir que vous aviez répondu)

**Comment by DelphinPETER** [comment]
Voir ma réponse : https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/issues/6#issuecomment-272471312
