### ISSUE TITLE
Definition de la retraction et de la premiere couche

### ISSUE THREAD

**Issue by DelphinPETER** [DelphinPETER/DiscoEasy200#8]
Info de jpg35 : 

J'ai comparé le fichier XML de Cura by Dagoma:

Il y a deux sections, voici la première : ;______________________________________________________________________________________________________________
;Definition de la retraction et de la premiere couche
;______________________________________________________________________________________________________________ <Config_Adv>
<retraction_speed>50</retraction_speed>
<retraction_amount>3.5</retraction_amount>
<bottom_thickness>0.26</bottom_thickness>
<layer0_width_factor>100</layer0_width_factor>
<object_sink>0</object_sink>
<cool_min_layer_time>10</cool_min_layer_time>
<fan_enabled>True</fan_enabled>
</Config_Adv>

Et les corrections que je propose pour les profiles de Cura 2.3.1:
<retraction_speed>50</retraction_speed>
il faut rajouter la ligne suivante a nos 3 profiles de Cura 2.3.1
retraction_speed = 50 (de base c'était déja le cas, mais autant la figer)

<retraction_amount>3.5</retraction_amount>
Degré supplémentaire de rétractation primaire:
qui doit génére "G1 F3000 E-3.5" après la phase d'initialisation dans le fichier "dagoma0.g"
retraction_extra_prime_amount = 3.5 (de base il y avait 0)

<bottom_thickness>0.26</bottom_thickness>
Normalement c'est un enfant de "Bottom/Top thickness" qui reprend cette valeur.
Bottom thickness (mm):
Détermine la hauteur de la couches imprimées sur le fond de l’objet.
Cette valeur doit toujours être un multiple de la hauteur de couche (x2 ou x3).
dans Cura 2.3.1: 1mm par défaut soit 5 couches en mode rapide et 10 couches en mode fin
à mon sens dans nom modèle par defaut
la valeur de 0.26 de CbD me parait étrange.
Si quelqu'un à une idée ?

<layer0_width_factor>100</layer0_width_factor>
J'ai lu un message sur le net où cette valeur devrait en faite être à 200
mais de toute facon, je ne retrouve pas ce paramètre dans Cura 2.3.1
Si quelqu'un à une idée ?

<object_sink>0</object_sink>
Si quelqu'un à une idée ?

<cool_min_layer_time>10</cool_min_layer_time>
cool_min_layer_time = 10 (de base c'était déja le cas, mais autant la figer)

<fan_enabled>True</fan_enabled>
cool_fan_enabled = true (de base c'était déjà le cas, mais autant la figer)

**Comment by jpg35310** [comment]
Suite lecture du fichier de Dagoma-Settings-For-Cura/suivi/Discoeasy200.txt
Suite compréhension des valeurs par défaut fixé dans resources\definitions\dagoma_discoeasy200.def.json
Suite compréhension des valeurs par défaut fixé dans  quality\dagoma_discoeasy200\*.*

Je te demande de clore ce ticket, je vais ouvrir un ticket par point précis.
(Je commence à comprendre)
