### ISSUE TITLE
Definition des caracteristiques du support

### ISSUE THREAD

**Issue by DelphinPETER** [DelphinPETER/DiscoEasy200#9]
Suite info de jpg35

Pour la deuxième section : "Definition des caracteristiques du support"
C'est en court, voici déjà les premiers éléments :

<retraction_min_travel>1.5</retraction_min_travel>
retraction_min_travel = 1.5 (de base il y avait 0.8)

<retraction_combing>True</retraction_combing>
Si quelqu'un à une idée ?

<retraction_minimal_extrusion>0.02</retraction_minimal_extrusion>
Si quelqu'un à une idée ?

<retraction_hop>0</retraction_hop>

<skirt_line_count>2</skirt_line_count>
<skirt_gap>3</skirt_gap>
<skirt_minimal_length>150</skirt_minimal_length>
<fan_full_height>0.5</fan_full_height>
A mon sens, il ne faut pas modifier ces trois valeurs qui etait identique pour CbD,
or dans Cura2.3.1 est sont spécifique à chaque profile.
et il y a déja des spécificités entre nos trois modèles.

<fan_speed>50</fan_speed>
cool_fan_speed_min = 50

<fan_speed_max>100</fan_speed_max>
cool_fan_speed_max = 100

<cool_min_feedrate>20</cool_min_feedrate>
Je comprends la vitesse minimal de fonctionnement du ventillateur
Dans Cura 2.3.1, ce semble fonctionner différement puisqu'il y les paramètre:

Durée minimale d'un couche (ce qui ralentie la vitesse d'impression !)
Vitesse minimal (ce qui empèche de trop ralentir)
<cool_head_lift>False</cool_head_lift>
Je pense, mais pas certain
cool_lift_head = flase (C'etait déja la valeur par defaut dans Cura 2.3.1)

<solid_top>True</solid_top>
support_enable = flase

<solid_bottom>True</solid_bottom>
Je laisse tomber, les supports c'est de toute manière du mode avancé.

Fin: Je bosse sur le reste.

**Comment by DelphinPETER** [comment]
Je ne sais pas si vous avez dejà vu ce fichier qui liste tous ce que j'ai déjà intégré.
https://github.com/DelphinPETER/Dagoma-Settings-For-Cura/blob/Cura_2.3/suivi/Discoeasy200.txt

**Comment by jpg35310** [comment]
Et non.... mais maintenant oui !

**Comment by jpg35310** [comment]
Suite lecture du fichier de Dagoma-Settings-For-Cura/suivi/Discoeasy200.txt
Suite compréhension des valeurs par défaut fixé dans resources\definitions\dagoma_discoeasy200.def.json
Suite compréhension des valeurs par défaut fixé dans quality\dagoma_discoeasy200*.*

Je te demande de clore ce ticket, je vais ouvrir un ticket par point précis.
(Je commence à comprendre)

**Comment by DelphinPETER** [comment]
Pas de souci, la prochaine étape c'est me proposer directement les modification dans les fichiers :)
